namespace :cleanup do
  desc 'Delete free sites with ≤ 1 block'
  task :sites => :environment do
    Site.joins(:blocks)
      .select { |site| site.blocks.size <= 1 && site.owner.plan == Plan.free }
      .each { |s| s.owner.destroy }
  end

  desc 'Delete junk'
  task :junk => :environment do
    %w(cookingstuff
    religiousjewellery
    taiwan-chartered-tour-of-people
    chaher
    protowtacoma
    square
    http-babyfairyforkid-upsite-io
    kry00
    rubyliou-test-space
    wellwisdom
    daelmo
    okahotel
    immat-cafe
    lab
    alan-konbini
    cloudcampus
    lovelord
    panda0905
    rco
    adil
    chenselect
    ou-wang-motorsports
    hatsune-miku
    kirin
    northland135
    nndv
    carabas
    cr
    jhweddingweb
    abzgallia
    nahitheper
    9bb0d39d-mohmal-im
    leven
    srio
    yang
    run4us
    diiin-studio
    louian
    only-you
    m37921
    longpingflower
    lanaufragaescritura
    fractalias
    pazo
    estudios-extranjeros
    nbshoes
    elsa0101
    areychiu
    izzydoesizzy
    angelvolk
    homemade-fruit-jam
    nickphotography
    sheldonsugar
    bubblepandatea
    exam
    latula
    davidlee
    morena
    matiasdutto-com
    kubens
    fernando-barahona
    modularwalls
    ethan-miffy
    iknowyoumissme
    aisuko-lee
    www-tradehappydeal-com
    yung-jou
    greglin
    ck
    crawfordbrien
    porn
    quinn
    geniwoo
    everywheresean
    uigds
    iiqian
    jesus-cosmos
    dory
    calebdelapiedra
    michaelworld
    1bakofrice-org
    koysd
    testing668
    freeaday
    queazmi
    nickbraund
    sur-andino
    testsite
    werbary
    pipi
    milkgy0730gtodogto
    designquotes
    easychen2016
    taomu-s-website
    yiyang
    toyking
    kuma-studio
    sam-road-garage
    http-nmflgj
    www-rnarch-com
    artyfarty
    ege
    rebecca
    xcaff
    grzegorz
    flosarocchi
    upsm-launcher
    nomino
    unimark_brush
    ltu
    matcha-wu
    yxtlsd
    aaronmcelwee
    brenda
    adenin
    paradigmadv
    atm
    niklausgerber
    interaxiona
    eaman
    alan922
    oatsandsugar
    51004
    visualog
    camilo
    digitally-evolved
    ars32
    marcoa
    creandoexperiencias-sadoth
    bolsas-artesanales
    eli
    johndo
    jerza
    aristotheme
    free
    alquiler-de-lanchas
    biga
    aa
    david-darnes
    beekaybikes
    vikara
    pau
    not-telling
    police95
    serddd
    cardoientile
    halohalonews
    jonathan-jennings
    bernal-photographer
    palermorusico
    festmsc
    byebea
    test_upsite
    x4
    parroquial
    neurosurgery-directory
    luis
    something
    francesco-onofri
    dsada
    hemsaigon
    mobile-parity
    nicolas-filzi
    offroadlights
    helder
    antonio-garcia
    dmark
    tom
    wdqwqwdq
    ferdi
    gemaachau
    elizabeth
    undefinedtoken
    frank
    risso
    adolfo
    hoi
    ltn
    gpritiranjan
    anton
    testowa
    sealpool
    cobb-pawn-gold
    babettescafe
    jonathan-brennan
    luigis-pizza156
    upscrape
    mindfulkids4london
    joseph-edwards-pc-repair
    adze-ybrant
    iliverse
    iliyan
    iliyanmc
    fernando-vinoly-special-events
    guisolfo
    martial-art
    definitely-maybe
    raravis-curious-store
    la-cucinella).each do |subdomain|
      s = Site.find_by(subdomain: subdomain)
      s.owner.destroy if s
    end
  end
end
